### ISSUE TITLE
Question : Verify commitment files generated by qaptools

### ISSUE THREAD

**Issue by lepilotedef22** [meilof/pysnark#12]
Hello,
I am using using the qaptools backend, and I am generating commitments using `gencomm`.
 Let's say I use it on a piece of data that I call `test`, so this will output the two files `pysnark_wires_test` and `pysnark_comm_test`, besides the key material. 
Is there a built-in function in the library that allows to check whether `pysnark_comm_test` is a valid commitment to `pysnark_wires_test` ?
Thank you in advance for your answer !

**Comment by meilof** [comment]
There is no built-in function to do exactly this (except that it if course
happens as part of the verification of the computation), but you could run
the qapinput tool on pysnark_wires_test and see if the output is the same
as in the commitment file. Running qapinput can be done from python by
adapting the run function from
https://github.com/meilof/pysnark/blob/master/pysnark/qaptools/runqapinput.py
so that it does not write to file but instead compares to what was
previously written to file. Hope that helps!

Op di 11 mei 2021 11:10 schreef lepilotedef22 ***@***.***>:

**Comment by lepilotedef22** [comment]
Thank you very much !
