### ISSUE TITLE
What is cube.py proving?

### ISSUE THREAD

**Issue by KoSpades** [meilof/pysnark#39]
Hi, I am new to ZKP, and I am just trying to understand what the examples are proving. I looked at public.json for cube.py, and the output contains both x and x^3, so what is this example proving?

**Comment by KoSpades** [comment]
Likewise, what is sudoku.py proving? If my understanding is correct, it is proving that prover possesses a solution to the puzzle, without revealing the solution itself?

I have another confusion about sudoku.py: I changed the solution array to an incorrect one, and ran the protocol again. But the verify step still outputs OK. Why is this?

I am going through the examples to try them out. I think an explanation of what each of the example is trying to prove would be super helpful!

**Comment by meilofveeningen-rl** [comment]
> Hi, I am new to ZKP, and I am just trying to understand what the examples are proving. I looked at public.json for cube.py, and the output contains both x and x^3, so what is this example proving?

This is just a demonstration. The point is that the verifier can learn that the output (x^3) is correct, without having to compute it themselves. Of course in this case, it is easy to do this computation, but for more complex computations it could in theory be faster to do verify the proof than to re-do the computation.

**Comment by meilofveeningen-rl** [comment]
> Likewise, what is sudoku.py proving? If my understanding is correct, it is proving that prover possesses a solution to the puzzle, without revealing the solution itself?

That is correct

> I have another confusion about sudoku.py: I changed the solution array to an incorrect one, and ran the protocol again. But the verify step still outputs OK. Why is this?

That is because you have ignore_error set to true. 

When you run pysnark for the first time for a given computation, it generates key material for doing the proofs, and also does the proof. When you run it again, the key material can be re-used, e.g., the verificaiton key material can be sent to a verifier.

However, in the sudoku use case that is a problem, because you need to succesfully run the computation in order to generate the key material. But what if you do not actually know the solution to the sudoku? Then you cannot run the computation succesfully. This is why the ignore_errors option is there. You can use this to run the program and generate the key material. Later you can use that key material to create and verify valid proofs. (The proof generated with ignore_errors set to True will not validate succesfully if there were errors.)

**Comment by KoSpades** [comment]
Thanks! I think this answers my questions.
